language: python

python:
  - "3.6"

services:
  - redis-server
  - xvfb

before_install:
  - sudo apt-get update -qq
  - export DISPLAY=:99.0

# command to install dependencies
install:
  - git clone https://github.com/FOSSEE/online_test.git fossee-online-test
  - cd fossee-online-test
# install depenedencies for fossee online test
  - pip install -r requirements/requirements-common.txt
  - python manage.py makemigrations
  - python manage.py migrate auth
  - python manage.py migrate
# start fossee-online-test
  - invoke serve &
  - cd ..
  - git clone https://github.com/FOSSEE/workshop_booking.git fossee-workshop
  - cd fossee-workshop
# install depenedencies for workshop
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate auth
  - python manage.py migrate
# start fossee-workshop
  - python manage.py runserver 5500 &
  - cd ..
# install depenedencies for task runner
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate auth
  - python manage.py migrate

# command to run tests and coverage
script:
# run the tests
  - celery -A taskrunner worker -l info
  - python manage.py test createcourse.tests.TestFetchDataTask

dist:
  xenial

addons:
  firefox: "46.0"
